### ISSUE TITLE
device-simulation.yaml error

### ISSUE THREAD

**Issue by sudhirkumar1980** [mspnp/iot-guidance#11]
export DRONE_DEVICESIMULATION_IMAGE={MyDeviceSimulationDockerImage}

what is value for MyDeviceSimulationDockerImage variable?

Getting error while deploying device-simulation.yaml. Followed all steps mentioned for Things/Devices

kubectl -n dronemgmt apply -f device-simulation.yaml
error: error validating "device-simulation.yaml": error validating data: ValidationError(StatefulSet.spec.template.spec.containers[0].image): invalid type for io.k8s.api.core.v1.Container.image: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by magrande** [comment]
@sudhirkumar1980   Thank you for raising this issue. The process that you are following to create the AKS cluster is out of date as it uses the legacy Azure Container Service (ACS). We suggest you follow the AKS Baseline implementation instead:

https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks

You will likely need to adapt the following set of commands to work with the current AKS implementation.
