### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by FabGre** [mspnp/iot-guidance#7]
Hello, 

did you planned to complete "TODO" in the main README file ?

Thanks !

**Comment by ckittel** [comment]
Sorry for the confusion, those were leftovers from a default readme template file.  To remove confusion, I've removed those sections.  That isn't to say we won't revisit this and add additional instructions, but doing so isn't on our backlog in the near term.  If there are any specific problems you're running into, or would like to contribute content to this, please don't hesitate to reach out.  Thanks.
